/// Which overhead picture each catalog crop is drawn with in Render, and
/// how big that picture is drawn.
///
/// One picture covers every crop that looks alike from above (all winter
/// squashes, all onions). Crops not listed keep the plain green circle.
abstract final class PlantArt {
  /// Share of a sprite's side left clear round the canopy; matches MARGIN
  /// in tools/render-art/plant_sprites.py.
  static const double spriteMargin = 0.02;

  /// The drawn canopy diameter, in metres, of catalog crop [cropId] at
  /// maturity seen from above, or null when it has no picture.
  ///
  /// Display only: spacing and counts come from the seed. Plants set at
  /// the catalog's spacing overlap along the row and leave the path
  /// between rows, as a grown bed does.
  static double? canopyOf(String? cropId) {
    final kind = kindOf(cropId);
    if (kind == null) return null;
    return (_cropSpreadIn[cropId] ?? _kindSpreadIn[kind]!) * _metresPerInch;
  }

  static const double _metresPerInch = 0.0254;

  /// Typical mature spread of each picture, in inches: a judged value
  /// from common growing guides, not from Johnny's, which gives only
  /// spacing.
  static const Map<String, double> _kindSpreadIn = {
    'lettuce': 10,
    'kale': 24,
    'cabbage': 20,
    'broccoli': 22,
    'cauliflower': 22,
    'pac_choi': 12,
    'chard': 14,
    'spinach': 8,
    'beet': 10,
    'carrot': 8,
    'turnip': 10,
    'potato': 20,
    'onion': 8,
    'chives': 8,
    'leek': 8,
    'garlic': 8,
    'tomato': 30,
    'pepper': 18,
    'eggplant': 24,
    'okra': 30,
    'corn': 24,
    'bean': 14,
    'pea': 10,
    'cucumber': 36,
    'summer_squash': 42,
    'winter_squash': 60,
    'melon': 60,
    'basil': 14,
    'parsley': 12,
    'celery': 12,
    'dill': 14,
    'thyme': 12,
    'rosemary': 24,
    'sage': 20,
    'mint': 18,
  };

  /// Crops much bigger or smaller than their picture's usual size:
  /// baby leaf cut young, trellised greenhouse crops, sprawling vines.
  static const Map<String, double> _cropSpreadIn = {
    'salad-mixes': 4,
    'arugula': 4,
    'baby-leaf-beets': 4,
    'baby-leaf-swiss-chard': 4,
    'baby-leaf-brassicas': 4,
    'chicory-baby-leaf': 4,
    'mache': 4,
    'cress': 5,
    'claytonia': 6,
    'purslane': 10,
    'dandelion': 8,
    'celtuce': 12,
    'chicory-endive-escarole': 12,
    'mustard': 12,
    'broccoli-raab': 10,
    'burdock': 24,
    'collards': 26,
    'leaf-broccoli': 14,
    'chinese-cabbage': 16,
    'brussels-sprouts': 24,
    'kohlrabi': 12,
    'mini-broccoli': 16,
    'asian-greens': 10,
    'malabar-spinach': 12,
    'magenta-spreen': 14,
    'orach': 12,
    'vegetable-amaranth': 14,
    'parsnip': 10,
    'pelleted-parsnips': 10,
    'radishes': 5,
    'daikon-radishes': 12,
    'rutabaga': 14,
    'horseradish': 24,
    'sweet-potatoes': 36,
    'bunching-onions': 6,
    'cipollini-mini-specialty-onions': 6,
    'lemon-grass': 24,
    'scorzonera-salsify': 6,
    'greenhouse-tomatoes': 18,
    'husk-cherry': 24,
    'tomatillo': 36,
    'greenhouse-peppers': 16,
    'greenhouse-eggplants': 20,
    'broom-corn': 30,
    'pole-bean': 10,
    'fava-bean': 16,
    'peas': 8,
    'greenhouse-cucumbers': 18,
    'ornamental-gourds': 48,
    'acorn-winter-squash': 48,
    'delicata-sweet-dumpling-winter-squash': 48,
    'hubbard-winter-squash': 84,
    'pumpkins': 84,
    'watermelons': 72,
    'cilantro-coriander': 8,
    'chervil': 8,
    'root-parsley': 10,
    'lovage': 24,
    'salad-burnet': 12,
    'asparagus': 24,
    'cumin': 8,
    'chamomile': 10,
    'mexican-mint-marigold': 18,
    'lavender': 20,
    'saltwort': 10,
    'borage': 18,
    'artichoke': 48,
    'cardoon': 48,
    'stevia': 14,
  };

  /// The picture kind for catalog crop [cropId], or null for none.
  static String? kindOf(String? cropId) =>
      cropId == null ? null : _kinds[cropId];

  /// Every crop ID that has a picture, for tests.
  static Iterable<String> get cropIds => _kinds.keys;

  static const Map<String, String> _kinds = {
    // Loose leafy salad greens.
    'lettuce': 'lettuce',
    'pelleted-lettuce': 'lettuce',
    'salad-mixes': 'lettuce',
    'arugula': 'lettuce',
    'celtuce': 'lettuce',
    'mache': 'lettuce',
    'claytonia': 'lettuce',
    'cress': 'lettuce',
    'chicory-baby-leaf': 'lettuce',
    'chicory-endive-escarole': 'lettuce',
    'chicory-belgian-endive': 'lettuce',
    'radicchio': 'lettuce',
    'italian-dandelion-chicory': 'lettuce',
    'dandelion': 'lettuce',
    'sorrel': 'lettuce',
    'purslane': 'lettuce',
    // Leafy brassicas.
    'kale': 'kale',
    'collards': 'kale',
    'kalettes': 'kale',
    'leaf-broccoli': 'kale',
    'baby-leaf-brassicas': 'kale',
    'mustard': 'kale',
    'flower-sprouts': 'kale',
    'broccoli-raab': 'kale',
    'burdock': 'kale',
    'cabbage': 'cabbage',
    'chinese-cabbage': 'cabbage',
    'brussels-sprouts': 'cabbage',
    'kohlrabi': 'cabbage',
    'broccoli': 'broccoli',
    'mini-broccoli': 'broccoli',
    'cauliflower': 'cauliflower',
    'pac-choi': 'pac_choi',
    'asian-greens': 'pac_choi',
    // Chard and spinach-like greens.
    'swiss-chard': 'chard',
    'baby-leaf-swiss-chard': 'chard',
    'spinach': 'spinach',
    'malabar-spinach': 'spinach',
    'magenta-spreen': 'spinach',
    'orach': 'spinach',
    'vegetable-amaranth': 'spinach',
    // Roots.
    'beets': 'beet',
    'pelleted-beets': 'beet',
    'baby-leaf-beets': 'beet',
    'carrots': 'carrot',
    'pelleted-carrots': 'carrot',
    'parsnip': 'carrot',
    'pelleted-parsnips': 'carrot',
    'turnips': 'turnip',
    'rutabaga': 'turnip',
    'radishes': 'turnip',
    'daikon-radishes': 'turnip',
    'horseradish': 'turnip',
    'potatoes': 'potato',
    'sweet-potatoes': 'potato',
    // Alliums and grassy clumps.
    'onions': 'onion',
    'pelleted-onions': 'onion',
    'onion-sets': 'onion',
    'cipollini-mini-specialty-onions': 'onion',
    'shallots': 'onion',
    'bunching-onions': 'onion',
    'chives': 'chives',
    'chinese-leeks-garlic-chives': 'chives',
    'lemon-grass': 'chives',
    'leeks': 'leek',
    'garlic': 'garlic',
    'scorzonera-salsify': 'garlic',
    // Fruiting plants.
    'tomatoes': 'tomato',
    'greenhouse-tomatoes': 'tomato',
    'tomatillo': 'tomato',
    'husk-cherry': 'tomato',
    'peppers': 'pepper',
    'greenhouse-peppers': 'pepper',
    'eggplant': 'eggplant',
    'greenhouse-eggplants': 'eggplant',
    'okra': 'okra',
    'corn-sweet': 'corn',
    'corn-super-sweet': 'corn',
    'corn-old-fashioned-sweet': 'corn',
    'corn-ornamental-dry-field': 'corn',
    'broom-corn': 'corn',
    // Legumes.
    'bush-bean': 'bean',
    'pole-bean': 'bean',
    'french-filet-beans': 'bean',
    'fresh-shell-bean': 'bean',
    'lima-bean': 'bean',
    'soybean': 'bean',
    'fava-bean': 'bean',
    'peas': 'pea',
    // Vines.
    'cucumber': 'cucumber',
    'greenhouse-cucumbers': 'cucumber',
    'ornamental-gourds': 'cucumber',
    'summer-squash': 'summer_squash',
    'zucchini': 'summer_squash',
    'yellow-summer-squash': 'summer_squash',
    'specialty-summer-squash': 'summer_squash',
    'winter-squash': 'winter_squash',
    'acorn-winter-squash': 'winter_squash',
    'buttercup-winter-squash': 'winter_squash',
    'butternut-winter-squash': 'winter_squash',
    'delicata-sweet-dumpling-winter-squash': 'winter_squash',
    'hubbard-winter-squash': 'winter_squash',
    'kabocha-winter-squash': 'winter_squash',
    'spaghetti-winter-squash': 'winter_squash',
    'pumpkins': 'winter_squash',
    'melons': 'melon',
    'watermelons': 'melon',
    // Herbs.
    'basil': 'basil',
    'shiso': 'basil',
    'parsley': 'parsley',
    'root-parsley': 'parsley',
    'chervil': 'parsley',
    'cilantro-coriander': 'parsley',
    'lovage': 'parsley',
    'salad-burnet': 'parsley',
    'celery-and-celeriac': 'celery',
    'cutting-celery': 'celery',
    'dill': 'dill',
    'fennel': 'dill',
    'leaf-fennel': 'dill',
    'pelleted-fennel': 'dill',
    'anise': 'dill',
    'caraway': 'dill',
    'cumin': 'dill',
    'asparagus': 'dill',
    'thyme': 'thyme',
    'marjoram': 'thyme',
    'wild-marjoram': 'thyme',
    'oregano-greek': 'thyme',
    'summer-savory': 'thyme',
    'winter-savory': 'thyme',
    'hyssop': 'thyme',
    'chamomile': 'thyme',
    'chamomile-roman': 'thyme',
    'mexican-mint-marigold': 'thyme',
    'rosemary': 'rosemary',
    'lavender': 'rosemary',
    'saltwort': 'rosemary',
    'sage': 'sage',
    'borage': 'sage',
    'artichoke': 'sage',
    'cardoon': 'sage',
    'mint': 'mint',
    'lemon-balm': 'mint',
    'anise-hyssop': 'mint',
    'stevia': 'mint',
  };
}
