// Opt-in actual Flutter raster proofs (never generated by ordinary tests):
// flutter test --no-pub --dart-define=EXPORT_TERRAIN_PROOFS=true \
//   test/presentation/terrain_proofs_test.dart
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:garden_gnome/application/camera.dart';
import 'package:garden_gnome/application/garden_controller.dart';
import 'package:garden_gnome/application/texture_library.dart';
import 'package:garden_gnome/application/toasts.dart';
import 'package:garden_gnome/application/workspace_settings.dart';
import 'package:garden_gnome/domain/grow/garden_record.dart';
import 'package:garden_gnome/domain/grow/variety.dart';
import 'package:garden_gnome/domain/layer.dart';
import 'package:garden_gnome/domain/vec.dart';
import 'package:garden_gnome/presentation/canvas/render_assets.dart';
import 'package:garden_gnome/presentation/canvas/render_cover.dart';
import 'package:garden_gnome/presentation/canvas/scene_painter.dart';
import 'package:garden_gnome/presentation/canvas/scene_state.dart';

import '../support/editor_input.dart';
import '../support/memory_garden_record_store.dart';
import '../support/render_fixtures.dart';
import '../support/texture_fixtures.dart';

const _export = bool.fromEnvironment('EXPORT_TERRAIN_PROOFS');
const _output = '../docs/concepts/whimsy/textures/rendered';

Future<ui.Image> _material(RenderAssets assets, RenderTexture texture) async {
  final image = assets.texture(texture)!;
  final grid = assets.atlasGrid(texture);
  final shader = assets.groundShader(texture)!;
  final small = assets.smallCopies(texture);
  final tint = texture.tint;
  final uniforms = <double>[
    0,
    0,
    80,
    texture.metres,
    image.width.toDouble(),
    image.height.toDouble(),
    texture.seed,
    texture == RenderTexture.loam ? 0 : 1,
    texture.variation,
    tint.r,
    tint.g,
    tint.b,
    tint.a,
    ...assets.meanColour(texture),
    0,
    texture.edgeNoise,
    grid.width,
    grid.height,
    small == null ? 1 : 3,
  ];
  for (var i = 0; i < uniforms.length; i++) {
    shader.setFloat(i, uniforms[i]);
  }
  shader.setImageSampler(0, image);
  shader.setImageSampler(1, small?.$1 ?? image);
  shader.setImageSampler(2, small?.$2 ?? image);
  final recorder = ui.PictureRecorder();
  ui.Canvas(recorder).drawRect(
    const ui.Rect.fromLTWH(0, 0, 1024, 1024),
    ui.Paint()..shader = shader,
  );
  final picture = recorder.endRecording();
  final result = await picture.toImage(1024, 1024);
  picture.dispose();
  return result;
}

Future<ui.Image> _scene(
  RenderAssets assets, {
  Camera camera = const Camera(),
}) async {
  final (editor, input) = newEditor();
  final property = rectangleLayer(
    editor,
    input,
    LayerKind.property,
    3,
    3,
    45,
    33,
  );
  String bed(double x, double y, double w, double h, GroundType? ground) {
    editor.selectLayer(property);
    final id = rectangleLayer(
      editor,
      input,
      LayerKind.zone,
      x,
      y,
      x + w,
      y + h,
    );
    if (ground != null) editor.setGround(id, ground);
    return id;
  }

  bed(5, 6, 10, 10, null);
  bed(18, 6, 10, 10, GroundType.flat);
  bed(31, 6, 10, 10, GroundType.row);
  final clover = bed(5, 20, 16, 10, GroundType.cover);
  final unknown = bed(25, 20, 16, 10, GroundType.cover);
  editor.setCover(
    clover,
    const CoverSowing(varietyId: 'v-clover', name: 'Crimson clover'),
  );
  editor.setCover(
    unknown,
    const CoverSowing(varietyId: 'unknown', name: 'Unknown cover'),
  );
  final garden = GardenController(
    store: MemoryGardenRecordStore(),
    toasts: ToastCenter(),
    record: GardenRecord(
      varieties: {
        'v-clover': const Variety(
          id: 'v-clover',
          cropId: 'crimson-clover',
          name: 'Crimson',
        ),
      },
    ),
  );
  addTearDown(garden.dispose);
  final covers = renderCoverCropIds(editor.document, garden);
  expect(covers, {clover: 'crimson-clover'});
  final recorder = ui.PictureRecorder();
  ScenePainter(
    SceneState(
      document: editor.document,
      camera: camera,
      appearance: const Appearance(),
      selectedLayerId: null,
      selection: const {},
      preview: null,
      lineAnchor: null,
      viewMode: ViewMode.render,
      renderAssets: assets,
      coverCropIds: covers,
    ),
  ).paint(ui.Canvas(recorder), const ui.Size(1440, 1080));
  final picture = recorder.endRecording();
  final image = await picture.toImage(1440, 1080);
  picture.dispose();
  return image;
}

Future<void> _save(
  ui.Image image,
  String name, {
  String output = _output,
}) async {
  final bytes = (await image.toByteData(format: ui.ImageByteFormat.png))!;
  final file = File('$output/$name.png');
  await file.parent.create(recursive: true);
  await file.writeAsBytes(
    bytes.buffer.asUint8List(bytes.offsetInBytes, bytes.lengthInBytes),
  );
  expect(await file.length(), greaterThan(0));
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test(
    'all materials and multi-ground ScenePainter rasterize controlled fixtures',
    () async {
      final picture = await png(64, 64);
      final library = memoryLibrary(
        picture: picture.buffer.asUint8List(
          picture.offsetInBytes,
          picture.lengthInBytes,
        ),
      );
      final assets = RenderAssets(
        bundle: MemoryRenderBundle({}),
        textures: library,
      );
      addTearDown(assets.dispose);
      await assets.loadGround();
      for (final t in RenderTexture.values) {
        expect(assets.atlasGrid(t), const ui.Size(3, 1));
        final image = await _material(assets, t);
        expect(image.width, 1024);
        final rgba = (await image.toByteData())!.buffer.asUint8List();
        expect(rgba[3], 255);
        expect(rgba[0], greaterThan(0));
        image.dispose();
      }
      final scene = await _scene(assets);
      expect(scene.width, 1440);
      final pixels = (await scene.toByteData())!.buffer.asUint8List();
      // Same source image: only unknown cover receives the generic green wash.
      final clover = (750 * 1440 + 390) * 4;
      final unknown = (750 * 1440 + 990) * 4;
      expect(pixels[unknown + 1], greaterThan(pixels[clover + 1]));
      final closeCamera = Camera(
        topLeft: const Vec(18, 15),
        height: Camera.heightFor(metres: 1, pixels: 160),
      );
      expect(closeCamera.pixelsPerMetreNow, closeTo(160, 1e-9));
      final close = await _scene(assets, camera: closeCamera);
      final closePixels = (await close.toByteData())!.buffer.asUint8List();
      // World (26, 21) is generic cover, not the overview's lawn here.
      final closeUnknown = (960 * 1440 + 1280) * 4;
      final closeClover = (960 * 1440 + 160) * 4;
      expect(
        closePixels[closeUnknown + 1],
        greaterThan(pixels[closeUnknown + 1]),
      );
      expect(
        closePixels[closeUnknown + 1],
        greaterThan(closePixels[closeClover + 1]),
      );
      close.dispose();
      scene.dispose();
    },
  );

  test(
    'export final runtime atlas shader proofs and complete Render scene',
    () async {
      final library = TextureLibrary(
        store: MemoryTextureStore(),
        preparer: FakePreparer(),
        readAsset: (asset) async =>
            (await rootBundle.load(asset)).buffer.asUint8List(),
      );
      final assets = RenderAssets(textures: library);
      addTearDown(assets.dispose);
      await assets.loadGround();
      // Fail before writing anything if any ground did not build.
      for (final t in RenderTexture.values) {
        expect(
          assets.atlasGrid(t).width,
          library.selected(t.ground).length,
          reason: '${t.ground.folder} did not build its blend',
        );
        expect(assets.groundShader(t), isNotNull);
      }
      for (final t in RenderTexture.values) {
        final image = await _material(assets, t);
        await _save(image, t.ground.folder);
        image.dispose();
      }
      final scene = await _scene(assets);
      await _save(scene, 'scene');
      scene.dispose();
    },
    skip: !_export,
  );
}
